# Generated by Django 3.2.2 on 2024-10-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0002_alter_hashtag_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hashtag',
            table='hashtag',
        ),
    ]
