# Generated by Django 3.2.2 on 2024-10-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0003_alter_hashtag_table'),
        ('place', '0013_auto_20220320_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='hashtags',
            field=models.ManyToManyField(blank=True, db_table='place_hashtags', to='hashtag.Hashtag'),
        ),
        migrations.AlterModelTable(
            name='place',
            table='place',
        ),
    ]
